name: 🍎 Deploy for Mac
on:
  push:
   tags:
     - '*'
jobs:
  release-osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: 🧑‍🔧 Build Release
      run: cargo build --release && make zip-mac

    - name: ⬆️ Get version
      id: get_version
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
    
    - name: 🧮 Set SHA
      id: shasum
      run: |
        echo ::set-output name=sha::"$(shasum -a 256 target/release/continous-deployment-mac.tar.gz | awk '{printf $1}')"

    - name: 🐣 Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
            Changes in this Release
            - First Change
            - Second Change
        draft: false
        prerelease: false

    - name: 🚀 Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/release/continous-deployment-mac.tar.gz
        asset_name: continous-deployment-mac.tar.gz
        asset_content_type: application/gzip

    - name: 🍺 Bump Brew
      env: 
        HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.token }}
      run: |
        brew tap tgotwig/continous-deployment
        brew bump-formula-pr -f --version=${{ steps.get_version.outputs.version }} --no-browse --no-audit \
        --sha256=${{ steps.shasum.outputs.sha }} \
        --url='https://github.com/tgotwig/continous-deployment/releases/download/${{ steps.get_version.outputs.version }}/continous-deployment-mac.tar.gz' \
        tgotwig/homebrew-continous-deployment/continous-deployment
